version: '3.8'

services:
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: microservice-app
    ports:
      - '3306:3306'


  elasticsearch:
    image: elasticsearch:8.8.1
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      discovery.type: single-node

  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: spcloud
      POSTGRES_PASSWORD: spcloud